/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        // Legacy colors (used by staff.astro, waiver.astro)
        'byoc-teal': '#D0E8E7',
        'byoc-pink': '#E6397F',
        'byoc-text-pink': '#C06C84',
        'byoc-white': '#FFFFFF',
        'byoc-gray': '#F5F5F5',
        // New design system (Stitch "Flourished Hearth")
        'background': '#fef9ed',
        'surface': '#fef9ed',
        'surface-bright': '#fef9ed',
        'surface-dim': '#dedace',
        'surface-variant': '#e7e2d6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8f3e7',
        'surface-container': '#f2ede2',
        'surface-container-high': '#ede8dc',
        'surface-container-highest': '#e7e2d6',
        'on-background': '#1d1c15',
        'on-surface': '#1d1c15',
        'on-surface-variant': '#444841',
        'primary': '#52634c',
        'primary-container': '#8b9d83',
        'primary-fixed': '#d5e8cb',
        'primary-fixed-dim': '#b9ccb0',
        'on-primary': '#ffffff',
        'on-primary-container': '#253420',
        'on-primary-fixed': '#101f0d',
        'on-primary-fixed-variant': '#3b4b36',
        'secondary': '#7b5455',
        'secondary-container': '#fdcbcb',
        'secondary-fixed': '#ffdad9',
        'secondary-fixed-dim': '#ecbbba',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#795354',
        'on-secondary-fixed': '#2f1314',
        'on-secondary-fixed-variant': '#603d3e',
        'tertiary': '#625e50',
        'tertiary-container': '#9d9887',
        'tertiary-fixed': '#e9e2d0',
        'tertiary-fixed-dim': '#ccc6b4',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#333024',
        'on-tertiary-fixed': '#1e1c10',
        'on-tertiary-fixed-variant': '#4a4739',
        'outline': '#747870',
        'outline-variant': '#c4c8be',
        'surface-tint': '#52634c',
        'inverse-surface': '#323029',
        'inverse-on-surface': '#f5f0e4',
        'inverse-primary': '#b9ccb0',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        // New design system fonts
        headline: ['Noto Serif', 'Georgia', 'serif'],
        body: ['Work Sans', 'system-ui', 'sans-serif'],
        label: ['Work Sans', 'system-ui', 'sans-serif'],
        // Legacy (used by staff/waiver)
        serif: ['Playfair Display', 'Georgia', 'serif'],
        script: ['Great Vibes', 'cursive'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
